config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:passwords, :registrations]
  mount Ckeditor::Engine => '/ckeditor'
  root 'posts#index'
  devise_for :users, skip: [:passwords, :registrations],
    controllers:{omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users do
    collection do
      patch 'update_name'
      patch 'update_email'
    end
  end
  resources :creators
  resources :chats
  resources :posts do
    collection do
      get ':id/author', to: 'posts#author', as: 'post_author'
    end
    resources :votes, except: :delete
    delete 'votes', to: 'votes#destroy'
  end
  namespace :admins do
    root 'static_page#home'
    resources :users
    resources :posts do
      collection do
       patch 'update_publish'
       patch 'update_timepublish'
       post 'preview'
       patch ':id/confirm', to: 'posts#confirm', as: 'confirm'
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  scope :search_title, ->(search) {
    where 'title LIKE ?', "%#{search}%" if search.present?
  }

  scope :search_category, ->(search) {
    where category: search if search.present?
  }

  scope :search_public_unpublic, ->(search) {
    where(publish: search == 'true') if search.present?
  }

  scope :search_suggest_unsuggest, ->(search) {
    where(suggest: search == 'true') if search.present?
  }

  scope :sort_time_public_asc, ->(search) {
    order publish_time: search == 'true' ? :desc : :asc if search.present?
  }

  scope :filter_all, (lambda do |params|
    search_title(params[:post_title]).search_category(params[:category])
                                     .search_public_unpublic(
                                       params[:publish]
                                     )
                                     .search_suggest_unsuggest(
                                       params[:suggest]
                                     )
                                     .sort_time_public_asc(
                                       params[:publish_time]
                                     )
  end)

  scope :suggest, -> { where suggest: true }
  scope :unsuggest, -> { where suggest: false }

  scope :set_current_time, -> { where('publish_time < ?', DateTime.now) }

  mount_uploader :thumbnail, ImageUploader
  mount_uploader :avatar, ImageUploader
  enum category: %i[study school family]

  has_many :votes

  def count_vote(vote_type)
    votes.where(vote_types: vote_type).count
  end

  def voted?(user)
    votes.where(user_id: user.id).present?
  end

  def check_publish_time?
    publish_time > DateTime.now
  end

  class << self
    def filter_post(params)
      Post.filter_all(params)
          .paginate page: params[:page], per_page: 20
    end

    def filter_index(params)
      Post.filter_all(params)
          .search_public_unpublic('true')
          .set_current_time
          .sort_time_public_asc('true')
          .paginate page: params[:page], per_page: 10
    end
  end
end

app/controllers/admins/posts_controller.rb
module Admins
  class PostsController < ApplicationController
    layout 'application'
    include PostsHelper

    before_action :authenticate_admin!
    before_action :find_post, except: %i[index new create]
    before_action :load_category, only: %i[index new edit]

    def index
      @posts = Post.filter_post params
      respond_to do |format|
        format.html
        format.js
      end
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new blog_params
      if @post.save
        redirect_to admins_posts_path
        flash[:success] = 'Post was successfully created.'
      else
        load_category
        render :new
      end
    end

    def edit; end

    def update
      if @post.update_attributes blog_params
        redirect_to admins_posts_path
        flash[:success] = 'Post was successfully updated.'
      else
        load_category
        render :edit
      end
    end

    def update_publish
      @post.update_attributes(publish: false)
    end

    def update_timepublish
      @post.update_attributes(publish_time: params[:publish_time])
      respond_to do |format|
        format.js { @post }
      end
    end

    private

    def find_post
      @post = Post.find_by id: params[:id]
    end

    def blog_params
      params.require(:post).permit(
        :title, :category, :thumbnail, :content, :publish,
        :suggest, :publish_time, :avatar, :author_name, :position, :age,
        :avatar
      )
    end

    def load_category
      @category = Post.categories.keys
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'users'
  before_action :authenticate_user!

  before_action :find_post, except: %i[index new create]
  before_action :find_vote, except: %i[index new create]

  def index
    @load_more = params[:load_more]
    @posts = Post.filter_index params
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    redirect_to posts_url unless @post.publish
  end

  def author; end

  private

  def find_post
    @post = Post.find_by id: params[:id]
    return if @post
    redirect_to posts_url
  end

  def find_vote
    @vote = if user_signed_in?
              @post.votes.find_by user_id: current_user.id
            else
              @post.votes.find_by guest_vote: cookies[:guest_vote]
            end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def default_image(post)
    if post.thumbnail.present?
      image_tag post.thumbnail, size: Settings.thumbnail_size_index
    else
      image_tag 'default.png', size: Settings.thumbnail_size_index
    end
  end

  def default_avatar(post)
    if post.avatar.present?
      image_tag post.avatar, size: Settings.thumbnail_size_index
    else
      image_tag 'background-author.png', size: Settings.thumbnail_size_index
    end
  end

  def avatar_author(post)
    if post.avatar.present?
      image_tag post.avatar
    else
      image_tag 'default.png'
    end
  end

  def open_popup?
    if session[:open_popup].nil?
      session[:open_popup] = true
      return true
    end
    false
  end

  def get_avatar_temp(params)
    path_avatar = "#{Pathname.new Rails.root}/public/#{params[:post][:avatar]}"
    return unless File.exist? path_avatar
    File.open(path_avatar)
  end

  def get_thumbnail_temp(params)
    path_thumbnail = "#{Pathname.new Rails.root}/public/"\
                     "#{params[:post][:thumbnail]}"
    return unless File.exist? path_thumbnail
    File.open(path_thumbnail)
  end
end

app/views/admins/posts/_filter.html.erb
<div id='fillter'>
	<div class='row'>
		<div class='col-md-12'>
			<p class="search-fillter">Search Fillter</p>
		</div>
	</div>
  <%= form_tag admins_posts_path, method: :get, remote: true do %>
  	<div class="row">
  		<div class="col-md-3">
  			  <%= label_tag 'Title' %>
			  <%= text_field_tag :post_title, params[:search],
			  	class: 'form-control' %>
  		</div>
  		<div class="col-md-2">
  			<%= label_tag 'Category' %>
		    <%= select_tag :category, options_for_select(@category,
		    	params[:search]), include_blank: true, class: 'form-control' %>
  		</div>
  		<div class="col-md-2">
  			<%= label_tag 'Public/UnPublic' %>
		    <%= select_tag :publish,
		    	options_for_select([["public", true], ["unpublic", false]],
		    		params[:search]), include_blank: true,
		    			class: 'form-control' %>
  		</div>
  		<div class="col-md-2">
  			<%= label_tag 'Suggest' %>
		    <%= select_tag :suggest,
		    	options_for_select([["suggest", true], ["unsuggest", false]],
		    		params[:search]), include_blank: true, 
		    			class: 'form-control' %>
  		</div>
  		<div class="col-md-2">
  			<%= label_tag 'Change/Sort' %>
		    <%= select_tag :publish_time,
		    	options_for_select([["DESC", true], ["ASC", false]],
		    		params[:search]), include_blank: true,
		    			class: 'form-control' %>
  		</div>
  		<div class="col-md-1">
			  <%= button_tag 'Seach',
			  	class: 'btn-search custom-btn form-control' do %>
			    	Search
			  <% end %>
  		</div>
  	</div>
  <% end %>
</div>

app/views/admins/posts/_form.html.erb
<%= form_for [:admins, @post], html: { multipart: true } do |f| %>
	<div class="row">
		<div class="col-md-7">
			<div class="row">
				<div class="col-md-3">
					<%= f.label :title, class: 'custom-label' %>
				</div>
				<div class="col-md-6">
					<%= f.text_field :title, class: "form-control" %>
					<div id="title-confirm"></div>
					<div id="title-error"></div>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :category, class: 'custom-label' %>
				</div>
				<div class="col-md-6">
					<%= f.select :category, @category %>
					<div id="category-confirm"></div>
					<div id="category-error"></div>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :publish_time, class: 'custom-label' %>
				</div>
				<div class="col-md-6">
	        <div class="form-group">
	    			<%= f.text_field :publish_time, id: 'time-public-update',
	    				class: 'form-control' %>
		        <div id="publish-time-confirm"></div>
		        <div id="publish-time-error"></div>
	        </div>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :publish, class: 'custom-label' %>
				</div>
				<div class="col-md-6">
					<%= f.check_box :publish %>
					<div id="publish-confirm"></div>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :suggest, class: 'custom-label' %>
				</div>
				<div class="col-md-6">
					<%= f.check_box :suggest %>
					<div id="suggest-confirm"></div>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :thumbnail, class: 'custom-label' %>
				</div>
				<div class="col-md-6">
					<% if @post.thumbnail? %>
						<%= image_tag @post.thumbnail_url, id: 'thumbnail-view',
							size: Settings.thumbnail_size %>
					<% else %>
						<%= image_tag 'default.png', id: 'thumbnail-view',
						 class: "image-create", size: Settings.thumbnail_size %>
					<% end %>
					<br>
					<br>
					<div id="input-thumbnail">
						<p>required/<=2MB/Only PNG,JPG</p>
	          <%= f.label :thumbnail, class: 'btn btn-default' do %>
	          	Open
	          <% end %>
						<%= f.file_field :thumbnail, class: 'upload-thumbnail' %>
					</div>
					<div id="thumbnail-error"></div>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :content, class: 'custom-label' %>
				</div>
				<div class="col-md-6">
          <%= link_to "Preview", 'javascript:void(0)', id: 'preview-btn',
                      'data-toggle' => 'modal',
                      'data-target' => '#preview-modal' %>
					<div id="body-content">
						<%= f.cktext_area :content, class: 'post-content' %>
					</div>
					<div id="content-confirm"></div>
					<div id="content-error"></div>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :author_name, class: 'custom-label' %>
				</div>
				<div class="col-md-6">
					<%= f.text_field :author_name, class: 'form-control' %>
					<div id="author-name-confirm"></div>
					<div id="author-name-error"></div>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :position, class: 'custom-label' %>
				</div>
				<div class="col-md-6">
					<%= f.text_field :position, class: 'form-control' %>
					<div id="position-confirm"></div>
					<div id="position-error"></div>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :age, class: 'custom-label' %>
				</div>
				<div class="col-md-6">
					<%= f.text_field :age, class: 'form-control' %>
					<div id="age-confirm"></div>
					<div id="age-error"></div>
					<div id="age-error-format"></div>
					<div id="age-error-number"></div>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :avatar, class: 'custom-label' %>
				</div>
				<div class="col-md-6">
					<% if @post.avatar? %>
						<%= image_tag @post.avatar, id: 'avatar-view',
							size: Settings.thumbnail_size %>
					<% else %>
						<%= image_tag 'background-author.png', id: 'avatar-view',
						 class: 'image-create', size: Settings.thumbnail_size %>
					<% end %>
					<br>
					<br>
					<div id="input-avatar">
						<p>required/<=2MB/Only PNG,JPG</p>
	          <%= f.label :avatar, class: 'btn btn-default' do %>
	          	Open
	          <% end %>
						<%= f.file_field :avatar, class: 'upload-avatar' %>
					</div>
					<div id="avatar-error"></div>
				</div>
			</div>
			<br>
			<%= f.submit yield(:button_text), class: 'btn-save hidden btn btn-primary' %>
			<div class="row before-confirm">
				<div class="col-md-3 col-md-offset-6">
					<%= link_to admins_posts_path, id: 'btn-list', class: 'btn btn-default confirm' do %>
						List
					<% end %>
				</div>
				<div class="col-md-3">
					<%= link_to "javascript:void(0)", id: 'btn-submit', class: 'btn btn-primary confirm' do %>
						<%= yield(:button_text) %>
					<% end %>
				</div>
			</div>
			<div class="row after-confirm hidden">
				<div class="col-md-3 col-md-offset-6">
					<%= link_to "javascript:void(0)", id: 'btn-cancel', class: 'btn btn-default confirm' do %>
						Cancel
					<% end %>
				</div>
				<div class="col-md-3">
					<%= link_to "javascript:void(0)", id: 'btn-confirm', class: 'btn btn-primary confirm' do %>
						Confirm
					<% end %>
				</div>
			</div>
		</div>
	</div>
<% end %>

<!-- Modal -->
<div class="modal fade" id="preview-modal" role="dialog">
  <div class="modal-dialog">

    <!-- Modal preview -->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Preview</h4>
      </div>
      <div id="content-preview" class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/admins/posts/_table.html.erb
<table class='table table-hover text-center'>
	<thead>
	  <tr>
	  	<th class='text-center'>ID</th>
	    <th class='text-center'>Time Create</th>
	    <th class='text-center'>Title</th>
	    <th class='text-center'>Category</th>
	    <th class='text-center'>Suggest</th>
	    <th class='text-center'>Author</th>
	    <th class='text-center'>Thumbnail</th>
	    <th class='text-center'>Publish/UnPublish</th>
	    <th class='text-center'>Date Publish</th>
	    <th class='text-center'>Action</th>
	  </tr>
	</thead>
	<tbody class='tbody-post'>
	  <% @posts.each_with_index do |post| %>
	    <tr>
	    	<td><%= post.id %></td>
	    	<td><%= post.created_at.strftime('%H:%M %d/%m/%Y') %></td>
	    	<td class="td-title"><%= post.title %></td>
	    	<td><%= post.category %></td>
	    	<td class='custom-suggest'>
	    		<%= post.suggest ? (image_tag 'circle.png') : '' %>
	    	</td>
	    	<td><%= post.author_name %></td>
	    	<td>
	    		<%= default_image post %>
	    	</td>
	    	<td id='set-status_<%= post.id %>'>
	    		<% if post.check_publish_time? %>
	    			Not Publish
	    		<% else %>
	    			<%= post.publish ? 'Publish' : 'Not Publish' %>
	    		<% end %>
	    	</td>
	    	<td>
	    		<p id='time-public_<%= post.id %>'>
	    			<%= post.publish_time.strftime('%Y-%m-%d %H:%M') if
	    				post.publish_time.present? %>
	    		</p>
	    		<p class="input-group">
	    			<input type='text' data_id='<%= post.id %>'
	    				id='input-time-public-update_<%= post.id %>' 
	    					value='<%= post.publish_time.strftime('%Y-%m-%d %H:%M') if
	    						post.publish_time.present? %>' 
	    							class='form-control time-public-update'>
	    		</p>
					<p id='edit-time-public_<%= post.id %>' 
						class='btn btn-default edit-time-public' 
							data_id='<%= post.id %>'>
								Edit
					</p>
					<% if !post.check_publish_time? && post.publish? %>
						<p id='set-private_<%= post.id %>'
							class='btn btn-danger set-private' 
								data_id='<%= post.id %>'>
								Private
						</p>
					<% end %>
	    		<p id='update-time-public_<%= post.id %>' 
	    			class='btn btn-primary update-time-public' 
	    				data_id='<%= post.id %>'>
	    					Update
	    		</p>
	    		<p id='cancel-time-public_<%= post.id %>' 
	    			class='btn btn-default cancel-time-public' 
	    				data_id='<%= post.id %>'>
	    					Cancel
	    		</p>
	    	</td>
	      <td>
	        <%= link_to edit_admins_post_path(post),
	        	class: 'custom-link-to btn-default' do %>
          		Edit
	        <% end %>
	      </td>
	    </tr>
	  <% end %>
	</tbody>
</table>

app/views/admins/posts/confirm.html.erb
<% provide :title, 'Confirm Update Blog' %>
<h1>Confirm Update Blog</h1>
<br>
<%= form_for [:admins, @post], url: confirm_admins_posts_path do |f| %>
	<div class="row">
		<div class="col-md-6">
			<div class="row">
				<div class="col-md-3">
					<%= f.label :title %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :title, value: @post.title %>
					<div>
						<%= @post.title %>
					</div>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :category %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :category, value: @post.category %>
					<%= @post.category %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :publish_time %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :publish_time, value: @post.publish_time.strftime('%H:%M %d/%m/%Y') if 
						@post.publish_time.present? %>
					<%= @post.publish_time.strftime('%H:%M %d/%m/%Y') if @post.publish_time.present? %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :publish %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :publish, value: @post.publish %>
					<%= @post.publish ? 'Publish' : 'Not Publish' %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :suggest %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :suggest, value: @post.suggest %>
					<%= @post.suggest ? 'Suggest' : 'Not Suggest' %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :thumbnail %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :thumbnail, value: @post.thumbnail_url %>
					<%= default_image @post %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :content %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :content, value: @post.content %>
					<div>
						<%= @post.content.html_safe if @post.content.present? %>
					</div>
				</div>
			</div>
			<br>
		</div>
		<div class="col-md-6">
			<div class="row">
				<div class="col-md-3">
					<%= f.label :author_name %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :author_name, value: @post.author_name %>
					<%= @post.author_name %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :position %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :position, value: @post.position %>
					<%= @post.position %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :age %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :age, value: @post.age %>
					<%= @post.age %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :avatar %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :avatar, value: @post.avatar_url %>
					<%= default_avatar @post %>
				</div>
			</div>
			<br>
		</div>
	</div>
	<div class="row">
		<div class="col-md-1 col-md-offset-5">
			<%= link_to "javascript:void(0)", class: 'button-back btn btn-default' do %>
				Back
			<% end %>
		</div>
		<div class="col-md-2">
			<%= f.submit "Save", class: 'btn btn-primary' %>
		</div>
	</div>
<% end %>

app/views/admins/posts/edit.html.erb
<% provide :title, 'Edit Blog' %>
<% provide :button_text, 'Update Blog' %>
<h1>Update Blog</h1>
<%= render 'form' %>

app/views/admins/posts/index.html.erb
<% provide :title, 'List Blog' %>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<h1>List Blog</h1>
<%= render 'filter' %>
<div class="btn-create-blog">
	<%= link_to new_admins_post_path, class: 'btn-primary' do %>
		Create Blog
	<% end %>
</div>
<div class="list-post">
	<div class="paginate">
		<%= will_paginate %>
	</div>
	<div class="table-filter">
		<%= render "table" %>
	</div>
	<div class="paginate">
		<%= will_paginate %>
	</div>
</div>

app/views/admins/posts/index.js.erb
$('.paginate').html('<%= j will_paginate @posts %>');
$('.table-filter').html('<%= j render "table" %>');
$('.paginate').html('<%= j will_paginate @posts %>');
choosedate();

app/views/admins/posts/new.html.erb
<% provide :title, 'New Blog' %>
<% provide :button_text, 'Create Blog' %>
<h1>Create Blog</h1>
<%= render 'form' %>

app/views/admins/posts/preview.html.erb
<% provide :title, 'Preview Blog' %>
<h1>Preview Blog</h1>
<br>
<%= form_for [:admins, @post], url: preview_admins_posts_path do |f| %>
	<div class="row">
		<div class="col-md-6">
			<div class="row">
				<div class="col-md-3">
					<%= f.label :title %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :title, value: @post.title %>
					<div>
						<%= @post.title %>
					</div>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :category %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :category, value: @post.category %>
					<%= @post.category %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :publish_time %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :publish_time, value: @post.publish_time.strftime('%H:%M %d/%m/%Y') if 
						@post.publish_time.present? %>
					<%= @post.publish_time.strftime('%H:%M %d/%m/%Y') if @post.publish_time.present? %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :publish %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :publish, value: @post.publish %>
					<%= @post.publish ? 'Publish' : 'Not Publish' %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :suggest %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :suggest, value: @post.suggest %>
					<%= @post.suggest ? 'Suggest' : 'Not Suggest' %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :thumbnail %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :thumbnail, value: @post.thumbnail_url %>
					<%= default_image @post %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :content %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :content, value: @post.content %>
					<div>
						<%= @post.content.html_safe if @post.content.present? %>
					</div>
				</div>
			</div>
			<br>
		</div>
		<div class="col-md-6">
			<div class="row">
				<div class="col-md-3">
					<%= f.label :author_name %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :author_name, value: @post.author_name %>
					<%= @post.author_name %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :position %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :position, value: @post.position %>
					<%= @post.position %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :age %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :age, value: @post.age %>
					<%= @post.age %>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-3">
					<%= f.label :avatar %>
				</div>
				<div class="col-md-6">
					<%= f.hidden_field :avatar, value: @post.avatar_url %>
					<%= default_avatar @post %>
				</div>
			</div>
			<br>
		</div>
	</div>
	<div class="row">
		<div class="col-md-1 col-md-offset-5">
			<%= link_to "javascript:history.back()", class: 'btn btn-default' do %>
				Back
			<% end %>
		</div>
		<div class="col-md-2">
			<%= f.submit "Save", class: 'btn btn-primary' %>
		</div>
	</div>
<% end %>

app/views/admins/posts/update_timepublish.js.erb
<% if @post.check_publish_time? %>
	$('#set-status_' + id).html('Not Publish');
	$('#set-private_' + id).addClass('hidden');
<% else %>
	<% if @post.publish? %>
		$('#set-status_' + id).html('Publish');
		$('#set-private_' + id).removeClass('hidden').removeAttr("style");
	<% else %>
		$('#set-status_' + id).html('Not Publish');
		$('#set-private_' + id).addClass('hidden');
	<% end %>
<% end %>