config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:passwords, :registrations]
  mount Ckeditor::Engine => '/ckeditor'
  root 'posts#index'
  devise_for :users, skip: [:passwords, :registrations],
    controllers:{omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users do
    collection do
      patch 'update_name'
      patch 'update_email'
    end
  end
  resources :creators
  resources :chats
  resources :posts do
    collection do
      get ':id/author', to: 'posts#author', as: 'post_author'
    end
    resources :votes, except: :delete
    delete 'votes', to: 'votes#destroy'
  end
  namespace :admins do
    root 'static_page#home'
    resources :users
    resources :posts do
      collection do
       patch 'update_publish'
       patch 'update_timepublish'
       post 'preview'
       patch ':id/confirm', to: 'posts#confirm', as: 'confirm'
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  scope :search_title, ->(search) {
    where 'title LIKE ?', "%#{search}%" if search.present?
  }

  scope :search_category, ->(search) {
    where category: search if search.present?
  }

  scope :search_public_unpublic, ->(search) {
    where(publish: search == 'true') if search.present?
  }

  scope :search_suggest_unsuggest, ->(search) {
    where(suggest: search == 'true') if search.present?
  }

  scope :sort_time_public_asc, ->(search) {
    order publish_time: search == 'true' ? :desc : :asc if search.present?
  }

  scope :filter_all, (lambda do |params|
    search_title(params[:post_title]).search_category(params[:category])
                                     .search_public_unpublic(
                                       params[:publish]
                                     )
                                     .search_suggest_unsuggest(
                                       params[:suggest]
                                     )
                                     .sort_time_public_asc(
                                       params[:publish_time]
                                     )
  end)

  scope :suggest, -> { where suggest: true }
  scope :unsuggest, -> { where suggest: false }

  scope :set_current_time, -> { where('publish_time < ?', DateTime.now) }

  mount_uploader :thumbnail, ImageUploader
  mount_uploader :avatar, ImageUploader
  enum category: %i[study school family]

  has_many :votes

  def count_vote(vote_type)
    votes.where(vote_types: vote_type).count
  end

  def voted?(user)
    votes.where(user_id: user.id).present?
  end

  def check_publish_time?
    publish_time > DateTime.now
  end

  class << self
    def filter_post(params)
      Post.filter_all(params)
          .paginate page: params[:page], per_page: 20
    end

    def filter_index(params)
      Post.filter_all(params)
          .search_public_unpublic('true')
          .set_current_time
          .sort_time_public_asc('true')
          .paginate page: params[:page], per_page: 10
    end
  end
end

app/controllers/admins/posts_controller.rb
module Admins
  class PostsController < ApplicationController
    layout 'application'
    include PostsHelper

    before_action :authenticate_admin!
    before_action :find_post, except: %i[index new create]
    before_action :load_category, only: %i[index new edit]

    def index
      @posts = Post.filter_post params
      respond_to do |format|
        format.html
        format.js
      end
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new blog_params
      if @post.save
        redirect_to admins_posts_path
        flash[:success] = 'Post was successfully created.'
      else
        load_category
        render :new
      end
    end

    def edit; end

    def update
      if @post.update_attributes blog_params
        redirect_to admins_posts_path
        flash[:success] = 'Post was successfully updated.'
      else
        load_category
        render :edit
      end
    end

    def update_publish
      @post.update_attributes(publish: false)
    end

    def update_timepublish
      @post.update_attributes(publish_time: params[:publish_time])
      respond_to do |format|
        format.js { @post }
      end
    end

    private

    def find_post
      @post = Post.find_by id: params[:id]
    end

    def blog_params
      params.require(:post).permit(
        :title, :category, :thumbnail, :content, :publish,
        :suggest, :publish_time, :avatar, :author_name, :position, :age,
        :avatar
      )
    end

    def load_category
      @category = Post.categories.keys
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'users'
  before_action :authenticate_user!

  before_action :find_post, except: %i[index new create]
  before_action :find_vote, except: %i[index new create]

  def index
    @load_more = params[:load_more]
    @posts = Post.filter_index params
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    redirect_to posts_url unless @post.publish
  end

  def author; end

  private

  def find_post
    @post = Post.find_by id: params[:id]
    return if @post
    redirect_to posts_url
  end

  def find_vote
    @vote = if user_signed_in?
              @post.votes.find_by user_id: current_user.id
            else
              @post.votes.find_by guest_vote: cookies[:guest_vote]
            end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def default_image(post)
    if post.thumbnail.present?
      image_tag post.thumbnail, size: Settings.thumbnail_size_index
    else
      image_tag 'default.png', size: Settings.thumbnail_size_index
    end
  end

  def default_avatar(post)
    if post.avatar.present?
      image_tag post.avatar, size: Settings.thumbnail_size_index
    else
      image_tag 'background-author.png', size: Settings.thumbnail_size_index
    end
  end

  def avatar_author(post)
    if post.avatar.present?
      image_tag post.avatar
    else
      image_tag 'default.png'
    end
  end

  def open_popup?
    if session[:open_popup].nil?
      session[:open_popup] = true
      return true
    end
    false
  end

  def get_avatar_temp(params)
    path_avatar = "#{Pathname.new Rails.root}/public/#{params[:post][:avatar]}"
    return unless File.exist? path_avatar
    File.open(path_avatar)
  end

  def get_thumbnail_temp(params)
    path_thumbnail = "#{Pathname.new Rails.root}/public/"\
                     "#{params[:post][:thumbnail]}"
    return unless File.exist? path_thumbnail
    File.open(path_thumbnail)
  end
end

app/views/posts/_count_vote.html.erb
<ul>
	<li>
		<%= image_tag 'lol.png' %>
		<span class="count-lol">
			<%= @post.count_vote 'lol' %>
		</span>
	</li>
	<li>
		<%= image_tag 'smile.png' %>
		<span class="count-smile">
			<%= @post.count_vote 'smile' %>
		</span>
	</li>
	<li>
		<%= image_tag 'cry.png' %>
		<span class="count-cry">
			<%= @post.count_vote 'cry' %>
		</span>
	</li>
	<li>
		<%= image_tag 'sad.png' %>
		<span class="count-sad">
			<%= @post.count_vote 'sad' %>
		</span>
	</li>
</ul>

app/views/posts/_menu_sort.html.erb
<ul>
	<li class='<%= "actived" if params[:category].blank? &&
		params[:suggest].blank? && params[:unsuggest].blank? %>'>
			<%= link_to posts_path, remote: true do %>
				All
			<% end %>
	</li>
	<li class='<%= "actived" if params[:suggest].present? &&
		params[:suggest] == "true" %>'>
			<%= link_to posts_path(suggest: 'true'), remote: true do %>
				Suggest
			<% end %>
	</li>
	<li class='<%= "actived" if params[:category].present? &&
		params[:category] == "study" %>'>
			<%= link_to posts_path(category: 'study'), remote: true do %>
				Study
			<% end %>
	</li>
	<li class='<%= "actived" if params[:category].present? &&
		params[:category] == "school" %>'>
			<%= link_to posts_path(category: 'school'), remote: true do %>
				School
			<% end %>
	</li>
	<li class='<%= "actived" if params[:category].present? &&
		params[:category] == "family" %>'>
			<%= link_to posts_path(category: 'family'), remote: true do %>
				Family
			<% end %>
	</li>
</ul>

app/views/posts/_popup_index.html.erb
<div class="modal fade" id="popup-index" tabindex="-1" role="dialog" aria-labelledby="popup-index" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body text-center">
        <%= image_tag 'popup-index.png' %>

        <%= link_to root_path, class: 'btn btn-blog' do %>
          <i class="fa fa-list pull-left"></i>
          記事一覧を見る
          <i class="fa fa-chevron-right pull-right arrow"></i>
        <% end %>

        <%= link_to creators_path, class: 'btn btn-profile' do %>
        	ナルフォード先生のプロフィールをみる
        	<i class="fa fa-chevron-right pull-right arrow"></i>
        <% end %>

      </div>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
  $('#popup-index').modal();
</script>

app/views/posts/_post.html.erb
<% if !@posts.nil? && @posts.size > 0 %>
	<% @posts.each do |post| %>
	 <div class="list-post">
		<div class="post-suggest_<%= post.suggest %>">
			<%= post.suggest ? image_tag('suggest.png') : "" %>
		</div>
		<div class="post-title">
			<%= link_to post_path(post) do %>
				<%= post.title %>
			<% end %>
		</div>
		<div class="post-category_<%= post.category %>">
			<%= post.category %>
		</div>
		<div class="post-publishtime">
			<%= post.publish_time.strftime('%d.%m.%Y') if post.publish_time.present? %>
		</div>
		<div class="post-vote">
			<ul>
				<li>
					<%= image_tag 'lol.png' %>
					<span><%= post.count_vote 'lol' %></span>
				</li>
				<li>
					<%= image_tag 'smile.png' %>
					<span><%= post.count_vote 'smile' %></span>
				</li>
				<li>
					<%= image_tag 'cry.png' %>
					<span><%= post.count_vote 'cry' %></span>
				</li>
				<li>
					<%= image_tag 'sad.png' %>
					<span><%= post.count_vote 'sad' %></span>
				</li>
			</ul>
		</div>
	 </div>
	<% end %>
<% end %>

app/views/posts/_share_post.html.erb
<div class="show-share-post">
	<ul>
		<li>
			<%= link_to "https://twitter.com/intent/tweet?url=http://localhost:3000/posts/#{@post.id}&text=#{@post.title}", class: 'twitter-share-post' do %>
				<%= image_tag 'twitter.png' %>
			<% end %>
		</li>
		<li>
			<%= link_to "https://www.facebook.com/sharer.php?u=http://localhost:3000/posts/#{@post.id}&text=#{@post.title}", class: 'facebook-share-post' do %>
				<%= image_tag 'facebook.png' %>
			<% end %>
		</li>
		<li>
			<%= link_to "https://lineit.line.me/share/ui?url=http://localhost:3000/posts/#{@post.id}&text=#{@post.title}", class: 'line-share-post' do %>
				<%= image_tag 'line.png' %>
			<% end %>
		</li>
	</ul>
</div>

app/views/posts/_vote.html.erb
<div class="vote row">
	<div class="title-vote">
		参考になったかな？
	</div>
		<div class="col-md-6 col-sm-6 col-xs-6">
			<div class="voted-lol vote-btn <%= 'actived-vote' if @vote.present? && @vote.vote_types == 'lol' %>" vote_type="lol" 
					vote_id="<%= @vote.id if @vote.present? %>">
					<span class="icon-lol">なるほど</span>
			</div>
		</div>
		<div class="col-md-6 col-sm-6 col-xs-6">
			<div class="voted-smile vote-btn <%= 'actived-vote' if @vote.present? && @vote.vote_types == 'smile' %>" vote_type="smile"
					vote_id="<%= @vote.id if @vote.present? %>">
					<span class="icon-smile">おもしろい</span>
			</div>
		</div>

		<div class="col-md-6 col-sm-6 col-xs-6">
			<div class="voted-cry vote-btn <%= 'actived-vote' if @vote.present? && @vote.vote_types == 'cry' %>" vote_type="cry"
					vote_id="<%= @vote.id if @vote.present? %>">
					<span class="icon-cry">難しい</span>
			</div>
		</div>
		<div class="col-md-6 col-sm-6 col-xs-6">
			<div class="voted-sad vote-btn <%= 'actived-vote' if @vote.present? && @vote.vote_types == 'sad' %>" vote_type="sad"
					vote_id="<%= @vote.id if @vote.present? %>">
						<span class="icon-sad">がっかり</span>
			</div>
		</div>
		<input type="hidden" value="<%= post.id %>" class="post-id"></input>
		<% if current_user.present? %>
			<input type="hidden" value="<%= current_user.id %>" class="user-id"></input>
		<% end %>
</div>

app/views/posts/author.html.erb
<% provide(:title, "#{@post.author_name}") %>
<% provide :btn_back do %>
	<%= link_to post_path(@post.id) do %>
		<i class="fa fa-chevron-left" aria-hidden="true"></i>
	<% end %>
<% end %>
<div class="container">
	<div class="show-post-author">
		<div class="show-author-backgroundimage">
			<%= image_tag 'background-author.png' %>
		</div>
		<div class="text1-show-author">
			イーアス塾 特別講師
		</div>
		<div class="text2-show-author">
			ナルフォード先生
		</div>
		<div class="show-author-name">
			<span>Name:</span>
			<%= @post.author_name %>		
		</div>
		<div class="show-author-position">
			<span>Position:</span>
			<%= @post.position %>		
		</div>
		<div class="show-author-age">
			<span>Age:</span>
			<%= @post.age %>		
		</div>
		<div class="image-title-show-author">
			<%= image_tag 'title.png' %>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<% provide :title, 'なるほどブログ' %>
<% provide :bell do %>
	<%= link_to "#" do %>
		<%= image_tag 'bell.png' %>
	<% end %>
<% end %>
<div class='scroll-menu'>
	<div class='menu-sort'>
		<%= render 'menu_sort' %>
	</div>
</div>
<div class="container">
	<div id="my-posts">
		<%= render "post" %>
	</div>
	<div id="infinite-scrolling">
	  <%= will_paginate %>
	</div>
</div>
<%= render 'popup_index' if open_popup? %>

app/views/posts/index.js.erb
//sort category
$('.menu-sort').html('<%= j render "menu_sort" %>');

//pagination loadmore
<% if params[:load_more].present? %>
	$('#my-posts').append('<%= j render "post" %>');
<% else %>
	$('#my-posts').html('<%= j render "post" %>');
<% end %>
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @posts, params: { load_more: "yes" } %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/posts/show.html.erb
<% provide :title, 'なるほどブログ' %>
<% provide :btn_back do %>
	<%= link_to posts_path do %>
		<i class="fa fa-chevron-left" aria-hidden="true"></i>
	<% end %>
<% end %>
<div class="container">
	<div class="show-post">
		<div class="suggest-show-post_<%= @post.suggest %>">
			<%= @post.suggest ? image_tag('suggest.png') : "" %>
		</div>
		<div class="title-show-post">
			<%= @post.title %>
		</div>
		<div class="hr-post"></div>
		<div class="category-show-post_<%= @post.category %>">
			<%= @post.category %>
		</div>
		<div class="publishtime-show-post">
			<%= @post.publish_time.strftime('%d.%m.%Y') if @post.publish_time.present? %>
		</div>
		<div class="vote-show-post">
			<%= render 'count_vote' %>
		</div>
		<div class="clearfix"></div>
		<%= render 'share_post' %>
		<div class="thumbnail-show-post">
			<%= image_tag @post.thumbnail if @post.thumbnail.present? %>
		</div>
		<div class="content-show-post">
			<%= @post.content.html_safe if @post.content.present? %>
		</div>
		<div class="author-show-post">
			<div class="avatar-author">
				<%= avatar_author @post %>
			</div>
			<div class="intro-author">
				この記事を書いた人
			</div>
			<div class="name-author">
				<%= @post.author_name %>
			</div>
			<div class="position-author">
				<%= @post.position %> / <%= @post.age %> Age
			</div>
			<div class="view-author">
				<%= link_to post_author_posts_path @post do %>
					ナルフォード先生のプロフィールを見る >
				<% end %>
			</div>
		</div>
		<%= render 'vote', post: @post %>
		<div class="share-post-bottom">
			<%= image_tag 'icon-share-post.png' %>&nbsp;SNSでシェアする
		</div>
		<%= render 'share_post' %>
		<br>
	</div>
</div>