config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:passwords, :registrations]
  mount Ckeditor::Engine => '/ckeditor'
  root 'posts#index'
  devise_for :users, skip: [:passwords, :registrations],
    controllers:{omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users do
    collection do
      patch 'update_name'
      patch 'update_email'
    end
  end
  resources :creators
  resources :chats
  resources :posts do
    collection do
      get ':id/author', to: 'posts#author', as: 'post_author'
    end
    resources :votes, except: :delete
    delete 'votes', to: 'votes#destroy'
  end
  namespace :admins do
    root 'static_page#home'
    resources :users
    resources :posts do
      collection do
       patch 'update_publish'
       patch 'update_timepublish'
       post 'preview'
       patch ':id/confirm', to: 'posts#confirm', as: 'confirm'
      end
    end
  end
end

app/views/layouts/_footer_user.html.erb
<footer>
	<ul class="nav navbar-nav">
		<li id="chat" class="<%= active_class(chats_path) %>">
			<% if user_signed_in? %>
				<%= link_to chats_path, class: 'text-center' do %>
					<div class="icon-footer icon-chat"></div>トーク
				<% end %>
			<% end %>
		</li>
		<li id="post" class="<%= active_class(posts_path) %>
			<%= active_class("/posts/#{@post.id}") if @post.present? %>
				<%= active_class(post_author_posts_path(@post)) if @post.present? %>">
					<%= link_to posts_path, class: 'text-center' do %>
						<div class="icon-footer icon-post"></div>ブログ
					<% end %>
		</li>
		<% if user_signed_in? %>
			<li id="profile" class="<%= active_class user_path(current_user.id) %>">
					<%= link_to user_path(current_user.id), class: 'text-center' do %>
						<div class="icon-footer icon-user"></div>プロフィール
					<% end %>
			</li>
		<% end %>
	</ul>
</footer>

app/views/layouts/_header.html.erb
<div id="menu-admin">
  <div class="container">
    <% if admin_signed_in? %>
      <ul>
       <li>
         <%= link_to admins_root_path do %>
          EMS-Blog
         <% end %>
       </li>
       <li class="dropdown">
        <span class="dropdown-toggle" data-toggle="dropdown">
          ブログ
          <span class="caret"></span>
        </span>
        <ul class="dropdown-menu">
          <li class="<%= active_class_admin(admins_posts_path) %>">
            <%= link_to admins_posts_path do %>
              ブログ記事一覧
            <% end %>
          </li>
          <li class="<%= active_class_admin(new_admins_post_path) %>">
            <%= link_to new_admins_post_path do %>
              ブログ記事新規作成
            <% end %>
          </li>
        </ul>
       </li>
       <li class="pull-right">
         <%= link_to destroy_admin_session_path, method: :delete do %>
          Logout
         <% end %>
       </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/layouts/_header_user.html.erb
<header>
	<div class="back">
		<%= yield :btn_back %>
	</div>
	<div class="bell">
		<%= yield :bell %>
	</div>
	<div class="title">
		<%= yield :title %>
	</div>
	<div class="signout">
		<%= yield :sign_out %>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <div id="admin">
      <%= render "layouts/header" %>
      <div class="container">
        <%= yield %>
      </div>
      <%= render "/layouts/footer" %>
    </div>
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "users", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "users",
      "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header_user" %>
    <%= yield %>
    <%= render "/layouts/footer_user" %>
  </body>
</html>